import { MigrationInterface, QueryRunner } from 'typeorm';

export class FakePosts1616775936351 implements MigrationInterface {
	public async up(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(
			`
            insert into post (title, text, "creatorId", "createdAt") values ('Phased', 'Object-based dedicated neural-net', 1, '2020-07-14T20:55:41Z');
            insert into post (title, text, "creatorId", "createdAt") values ('tangible', 'Horizontal multi-tasking matrix', 1, '2020-09-17T03:15:11Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Graphic Interface', 'Re-engineered contextually-based project', 1, '2020-10-11T11:06:42Z');
            insert into post (title, text, "creatorId", "createdAt") values ('full-range', 'Enhanced user-facing service-desk', 1, '2021-02-26T22:39:51Z');
            insert into post (title, text, "creatorId", "createdAt") values ('forecast', 'Proactive multi-state knowledge base', 1, '2020-06-07T07:11:54Z');
            insert into post (title, text, "creatorId", "createdAt") values ('project', 'Proactive 3rd generation matrices', 1, '2020-12-29T16:16:23Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Fully-configurable', 'Sharable bottom-line product', 1, '2020-04-05T22:08:15Z');
            insert into post (title, text, "creatorId", "createdAt") values ('standardization', 'Robust optimal flexibility', 1, '2020-06-16T07:18:01Z');
            insert into post (title, text, "creatorId", "createdAt") values ('human-resource', 'Open-architected scalable standardization', 1, '2021-01-06T07:18:28Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Pre-emptive', 'Total fault-tolerant project', 1, '2020-04-13T12:46:38Z');
            insert into post (title, text, "creatorId", "createdAt") values ('cohesive', 'Decentralized coherent infrastructure', 1, '2021-01-20T10:31:51Z');
            insert into post (title, text, "creatorId", "createdAt") values ('bifurcated', 'Advanced bifurcated capability', 1, '2020-08-19T12:40:05Z');
            insert into post (title, text, "creatorId", "createdAt") values ('alliance', 'Progressive executive core', 1, '2020-06-06T14:19:04Z');
            insert into post (title, text, "creatorId", "createdAt") values ('monitoring', 'Assimilated stable functionalities', 1, '2020-05-08T18:11:11Z');
            insert into post (title, text, "creatorId", "createdAt") values ('help-desk', 'Balanced human-resource hardware', 1, '2020-05-26T15:49:35Z');
            insert into post (title, text, "creatorId", "createdAt") values ('matrix', 'Managed systematic hub', 1, '2020-08-21T18:19:45Z');
            insert into post (title, text, "creatorId", "createdAt") values ('static', 'Optional solution-oriented array', 1, '2021-02-12T17:36:42Z');
            insert into post (title, text, "creatorId", "createdAt") values ('optimizing', 'Multi-channelled attitude-oriented projection', 1, '2020-10-09T10:26:37Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Secured', 'Persevering hybrid analyzer', 1, '2020-06-12T08:30:10Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Monitored', 'Future-proofed needs-based workforce', 1, '2020-04-12T01:03:52Z');
            insert into post (title, text, "creatorId", "createdAt") values ('optimizing', 'Profit-focused zero tolerance projection', 1, '2020-06-17T19:14:47Z');
            insert into post (title, text, "creatorId", "createdAt") values ('customer loyalty', 'Centralized asynchronous extranet', 1, '2020-06-17T22:59:14Z');
            insert into post (title, text, "creatorId", "createdAt") values ('analyzing', 'Self-enabling upward-trending standardization', 1, '2020-04-29T06:21:12Z');
            insert into post (title, text, "creatorId", "createdAt") values ('heuristic', 'Up-sized value-added process improvement', 1, '2021-01-03T03:26:03Z');
            insert into post (title, text, "creatorId", "createdAt") values ('hybrid', 'Function-based intangible matrices', 1, '2020-10-01T01:59:04Z');
            insert into post (title, text, "creatorId", "createdAt") values ('coherent', 'Vision-oriented foreground hardware', 1, '2020-11-12T15:17:43Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Profound', 'Triple-buffered didactic workforce', 1, '2020-12-03T05:00:18Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Monitored', 'Robust human-resource product', 1, '2020-09-25T16:57:19Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Organic', 'Profit-focused secondary Graphical User Interface', 1, '2020-11-19T02:43:27Z');
            insert into post (title, text, "creatorId", "createdAt") values ('solution', 'Team-oriented bottom-line info-mediaries', 1, '2020-05-08T06:48:14Z');
            insert into post (title, text, "creatorId", "createdAt") values ('hierarchy', 'Organized well-modulated strategy', 1, '2020-10-02T00:49:04Z');
            insert into post (title, text, "creatorId", "createdAt") values ('pricing structure', 'Synergized responsive encoding', 1, '2021-03-09T12:47:50Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Cloned', 'Synergized holistic encryption', 1, '2020-04-14T19:01:47Z');
            insert into post (title, text, "creatorId", "createdAt") values ('core', 'Polarised national task-force', 1, '2020-12-28T07:32:49Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Cross-platform', 'Multi-lateral 5th generation array', 1, '2020-08-25T04:32:05Z');
            insert into post (title, text, "creatorId", "createdAt") values ('intranet', 'Virtual national emulation', 1, '2020-05-29T11:20:26Z');
            insert into post (title, text, "creatorId", "createdAt") values ('framework', 'Balanced 5th generation forecast', 1, '2020-06-12T04:48:40Z');
            insert into post (title, text, "creatorId", "createdAt") values ('monitoring', 'Persevering motivating groupware', 1, '2020-06-14T19:06:20Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Profit-focused', 'Profit-focused mission-critical implementation', 1, '2020-11-30T04:18:47Z');
            insert into post (title, text, "creatorId", "createdAt") values ('leading edge', 'Sharable multi-state matrix', 1, '2020-04-24T15:40:07Z');
            insert into post (title, text, "creatorId", "createdAt") values ('content-based', 'Pre-emptive responsive capability', 1, '2021-03-09T03:04:34Z');
            insert into post (title, text, "creatorId", "createdAt") values ('heuristic', 'Decentralized heuristic knowledge base', 1, '2020-11-15T06:32:16Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Multi-lateral', 'Grass-roots logistical definition', 1, '2020-09-24T21:01:42Z');
            insert into post (title, text, "creatorId", "createdAt") values ('client-server', 'Streamlined user-facing core', 1, '2020-06-04T15:46:16Z');
            insert into post (title, text, "creatorId", "createdAt") values ('challenge', 'Switchable eco-centric customer loyalty', 1, '2020-07-11T10:01:49Z');
            insert into post (title, text, "creatorId", "createdAt") values ('regional', 'Self-enabling multimedia approach', 1, '2020-03-29T14:11:08Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Profit-focused', 'Proactive bottom-line hierarchy', 1, '2021-01-31T18:03:07Z');
            insert into post (title, text, "creatorId", "createdAt") values ('groupware', 'Fundamental secondary utilisation', 1, '2020-05-07T04:47:31Z');
            insert into post (title, text, "creatorId", "createdAt") values ('user-facing', 'Fully-configurable regional flexibility', 1, '2021-02-24T05:07:51Z');
            insert into post (title, text, "creatorId", "createdAt") values ('initiative', 'Optional intangible application', 1, '2020-10-14T05:45:34Z');
            insert into post (title, text, "creatorId", "createdAt") values ('client-driven', 'Quality-focused exuding artificial intelligence', 1, '2020-07-31T12:41:05Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Fundamental', 'Inverse global contingency', 1, '2020-12-21T10:09:13Z');
            insert into post (title, text, "creatorId", "createdAt") values ('methodical', 'Synergized tertiary analyzer', 1, '2020-04-14T04:27:42Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Devolved', 'Public-key content-based hub', 1, '2020-11-28T13:19:20Z');
            insert into post (title, text, "creatorId", "createdAt") values ('standardization', 'Mandatory global analyzer', 1, '2021-03-19T20:31:44Z');
            insert into post (title, text, "creatorId", "createdAt") values ('zero defect', 'Mandatory systematic frame', 1, '2021-01-05T08:51:41Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Graphical User Interface', 'Business-focused bandwidth-monitored intranet', 1, '2020-10-29T00:17:59Z');
            insert into post (title, text, "creatorId", "createdAt") values ('next generation', 'Re-engineered hybrid circuit', 1, '2021-01-06T00:48:16Z');
            insert into post (title, text, "creatorId", "createdAt") values ('internet solution', 'User-friendly clear-thinking attitude', 1, '2020-08-10T23:52:32Z');
            insert into post (title, text, "creatorId", "createdAt") values ('infrastructure', 'Upgradable discrete project', 1, '2020-07-06T05:08:43Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Managed', 'Seamless multi-state hub', 1, '2020-03-29T19:21:21Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Persistent', 'User-centric encompassing customer loyalty', 1, '2020-11-07T20:00:20Z');
            insert into post (title, text, "creatorId", "createdAt") values ('collaboration', 'Enhanced systemic challenge', 1, '2020-05-01T08:30:47Z');
            insert into post (title, text, "creatorId", "createdAt") values ('groupware', 'Down-sized high-level productivity', 1, '2020-07-21T14:43:10Z');
            insert into post (title, text, "creatorId", "createdAt") values ('static', 'User-centric discrete info-mediaries', 1, '2020-11-11T00:12:10Z');
            insert into post (title, text, "creatorId", "createdAt") values ('web-enabled', 'User-friendly regional migration', 1, '2020-09-05T08:24:38Z');
            insert into post (title, text, "creatorId", "createdAt") values ('optimal', 'Synergized non-volatile complexity', 1, '2020-12-23T12:13:06Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Extended', 'Networked optimizing hardware', 1, '2020-11-13T00:16:21Z');
            insert into post (title, text, "creatorId", "createdAt") values ('impactful', 'Streamlined 6th generation functionalities', 1, '2020-09-25T08:28:35Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Open-source', 'Optimized intermediate concept', 1, '2020-12-31T18:53:25Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Re-engineered', 'Multi-lateral neutral archive', 1, '2021-01-26T10:17:47Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Quality-focused', 'Fundamental bifurcated encryption', 1, '2020-07-12T04:33:50Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Graphic Interface', 'Extended neutral flexibility', 1, '2020-09-19T10:27:58Z');
            insert into post (title, text, "creatorId", "createdAt") values ('neutral', 'Upgradable needs-based framework', 1, '2021-03-21T20:58:07Z');
            insert into post (title, text, "creatorId", "createdAt") values ('conglomeration', 'Up-sized responsive conglomeration', 1, '2020-12-01T12:25:12Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Innovative', 'Monitored global instruction set', 1, '2020-04-14T17:13:09Z');
            insert into post (title, text, "creatorId", "createdAt") values ('encryption', 'Profit-focused 6th generation knowledge base', 1, '2021-03-05T11:08:05Z');
            insert into post (title, text, "creatorId", "createdAt") values ('protocol', 'Future-proofed even-keeled success', 1, '2020-10-06T15:32:06Z');
            insert into post (title, text, "creatorId", "createdAt") values ('secured line', 'Function-based value-added service-desk', 1, '2020-04-27T04:16:13Z');
            insert into post (title, text, "creatorId", "createdAt") values ('hybrid', 'Programmable coherent help-desk', 1, '2020-08-12T17:12:14Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Assimilated', 'Right-sized 24/7 architecture', 1, '2021-01-29T15:00:18Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Object-based', 'Upgradable mission-critical open architecture', 1, '2020-09-24T15:39:47Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Graphic Interface', 'Centralized full-range pricing structure', 1, '2020-07-16T21:24:17Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Digitized', 'Virtual system-worthy forecast', 1, '2020-10-10T05:27:25Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Pre-emptive', 'Seamless heuristic access', 1, '2020-08-16T09:09:17Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Optional', 'Managed user-facing conglomeration', 1, '2021-02-14T08:09:19Z');
            insert into post (title, text, "creatorId", "createdAt") values ('superstructure', 'Triple-buffered object-oriented knowledge base', 1, '2020-12-16T06:34:57Z');
            insert into post (title, text, "creatorId", "createdAt") values ('next generation', 'Re-contextualized background data-warehouse', 1, '2020-05-05T02:56:46Z');
            insert into post (title, text, "creatorId", "createdAt") values ('encompassing', 'Stand-alone encompassing info-mediaries', 1, '2020-05-06T15:13:59Z');
            insert into post (title, text, "creatorId", "createdAt") values ('client-server', 'Optimized logistical analyzer', 1, '2020-11-26T09:54:22Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Configurable', 'Quality-focused content-based knowledge base', 1, '2021-03-11T11:44:39Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Fully-configurable', 'Object-based even-keeled service-desk', 1, '2020-08-28T05:16:16Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Operative', 'Multi-layered 24 hour capacity', 1, '2020-11-12T00:07:20Z');
            insert into post (title, text, "creatorId", "createdAt") values ('local', 'Pre-emptive mission-critical moderator', 1, '2020-10-05T13:33:54Z');
            insert into post (title, text, "creatorId", "createdAt") values ('throughput', 'Ergonomic optimal moderator', 1, '2021-01-05T20:13:33Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Robust', 'Ameliorated radical data-warehouse', 1, '2021-02-11T05:25:14Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Fundamental', 'Reverse-engineered responsive pricing structure', 1, '2021-01-14T07:07:14Z');
            insert into post (title, text, "creatorId", "createdAt") values ('Fundamental', 'Reactive uniform ability', 1, '2021-03-06T14:08:50Z');
            insert into post (title, text, "creatorId", "createdAt") values ('hybrid', 'Up-sized client-server paradigm', 1, '2020-08-23T03:54:19Z');
            insert into post (title, text, "creatorId", "createdAt") values ('groupware', 'Digitized 4th generation data-warehouse', 1, '2020-07-26T17:40:09Z');            
            `
		);
	}

	public async down(_: QueryRunner): Promise<void> {}
}
