import { MigrationInterface, QueryRunner } from 'typeorm';

export class FakePosts1616604203037 implements MigrationInterface {
	public async up(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`
            insert into post (title, text, "creatorId") values ('Exclusive', 'Managed client-driven firmware', 1);
            insert into post (title, text, "creatorId") values ('bi-directional', 'Fully-configurable web-enabled open system', 1);
            insert into post (title, text, "creatorId") values ('Profit-focused', 'Customer-focused coherent software', 1);
            insert into post (title, text, "creatorId") values ('hierarchy', 'Public-key attitude-oriented paradigm', 1);
            insert into post (title, text, "creatorId") values ('Streamlined', 'Grass-roots multi-tasking protocol', 1);
            insert into post (title, text, "creatorId") values ('hybrid', 'Optimized systemic model', 1);
            insert into post (title, text, "creatorId") values ('definition', 'Networked object-oriented frame', 1);
            insert into post (title, text, "creatorId") values ('paradigm', 'Progressive zero defect strategy', 1);
            insert into post (title, text, "creatorId") values ('modular', 'Public-key hybrid firmware', 1);
            insert into post (title, text, "creatorId") values ('local area network', 'Future-proofed empowering paradigm', 1);
            insert into post (title, text, "creatorId") values ('instruction set', 'Focused human-resource leverage', 1);
            insert into post (title, text, "creatorId") values ('middleware', 'Face to face tertiary artificial intelligence', 1);
            insert into post (title, text, "creatorId") values ('Open-architected', 'Balanced neutral moratorium', 1);
            insert into post (title, text, "creatorId") values ('encoding', 'Robust high-level hub', 1);
            insert into post (title, text, "creatorId") values ('workforce', 'Mandatory content-based help-desk', 1);
            insert into post (title, text, "creatorId") values ('Monitored', 'Future-proofed mission-critical productivity', 1);
            insert into post (title, text, "creatorId") values ('multimedia', 'Synchronised optimal instruction set', 1);
            insert into post (title, text, "creatorId") values ('collaboration', 'Re-engineered 24/7 moratorium', 1);
            insert into post (title, text, "creatorId") values ('frame', 'Phased contextually-based approach', 1);
            insert into post (title, text, "creatorId") values ('portal', 'Phased static monitoring', 1);
            insert into post (title, text, "creatorId") values ('Graphical User Interface', 'Advanced directional instruction set', 1);
            insert into post (title, text, "creatorId") values ('function', 'Face to face optimal monitoring', 1);
            insert into post (title, text, "creatorId") values ('workforce', 'Re-contextualized solution-oriented capability', 1);
            insert into post (title, text, "creatorId") values ('Total', 'Customer-focused directional data-warehouse', 1);
            insert into post (title, text, "creatorId") values ('Compatible', 'Exclusive responsive benchmark', 1);
            insert into post (title, text, "creatorId") values ('matrices', 'Pre-emptive tertiary budgetary management', 1);
            insert into post (title, text, "creatorId") values ('data-warehouse', 'Re-contextualized bi-directional utilisation', 1);
            insert into post (title, text, "creatorId") values ('web-enabled', 'Assimilated logistical methodology', 1);
            insert into post (title, text, "creatorId") values ('Polarised', 'User-friendly fault-tolerant frame', 1);
            insert into post (title, text, "creatorId") values ('software', 'Upgradable methodical functionalities', 1);
            insert into post (title, text, "creatorId") values ('Realigned', 'Reactive responsive standardization', 1);
            insert into post (title, text, "creatorId") values ('multi-state', 'Programmable fresh-thinking utilisation', 1);
            insert into post (title, text, "creatorId") values ('Future-proofed', 'Organic zero tolerance matrices', 1);
            insert into post (title, text, "creatorId") values ('logistical', 'Synchronised dedicated moratorium', 1);
            insert into post (title, text, "creatorId") values ('maximized', 'Front-line zero tolerance knowledge user', 1);
            insert into post (title, text, "creatorId") values ('ability', 'Sharable executive contingency', 1);
            insert into post (title, text, "creatorId") values ('middleware', 'Enhanced maximized moratorium', 1);
            insert into post (title, text, "creatorId") values ('Vision-oriented', 'Inverse empowering neural-net', 1);
            insert into post (title, text, "creatorId") values ('open system', 'Advanced heuristic synergy', 1);
            insert into post (title, text, "creatorId") values ('Switchable', 'Synergized system-worthy array', 1);
            insert into post (title, text, "creatorId") values ('Reactive', 'Adaptive exuding frame', 1);
            insert into post (title, text, "creatorId") values ('success', 'Integrated discrete parallelism', 1);
            insert into post (title, text, "creatorId") values ('logistical', 'Customer-focused directional synergy', 1);
            insert into post (title, text, "creatorId") values ('emulation', 'Managed client-server process improvement', 1);
            insert into post (title, text, "creatorId") values ('Automated', 'Cross-group systematic definition', 1);
            insert into post (title, text, "creatorId") values ('capability', 'Upgradable background service-desk', 1);
            insert into post (title, text, "creatorId") values ('Configurable', 'Phased homogeneous challenge', 1);
            insert into post (title, text, "creatorId") values ('Digitized', 'Face to face multimedia structure', 1);
            insert into post (title, text, "creatorId") values ('moderator', 'Triple-buffered 6th generation core', 1);
            insert into post (title, text, "creatorId") values ('Streamlined', 'Ergonomic explicit process improvement', 1);
            insert into post (title, text, "creatorId") values ('infrastructure', 'Adaptive 24 hour help-desk', 1);
            insert into post (title, text, "creatorId") values ('Fully-configurable', 'User-centric impactful initiative', 1);
            insert into post (title, text, "creatorId") values ('ability', 'Sharable background internet solution', 1);
            insert into post (title, text, "creatorId") values ('discrete', 'Pre-emptive bandwidth-monitored product', 1);
            insert into post (title, text, "creatorId") values ('structure', 'Profound optimizing standardization', 1);
            insert into post (title, text, "creatorId") values ('intranet', 'Programmable eco-centric extranet', 1);
            insert into post (title, text, "creatorId") values ('Optimized', 'Cross-group explicit database', 1);
            insert into post (title, text, "creatorId") values ('uniform', 'Realigned even-keeled array', 1);
            insert into post (title, text, "creatorId") values ('bi-directional', 'Public-key neutral attitude', 1);
            insert into post (title, text, "creatorId") values ('Integrated', 'Up-sized intermediate project', 1);
            insert into post (title, text, "creatorId") values ('multi-state', 'Configurable radical Graphical User Interface', 1);
            insert into post (title, text, "creatorId") values ('actuating', 'Ergonomic logistical utilisation', 1);
            insert into post (title, text, "creatorId") values ('Switchable', 'Extended dynamic synergy', 1);
            insert into post (title, text, "creatorId") values ('analyzer', 'De-engineered scalable projection', 1);
            insert into post (title, text, "creatorId") values ('client-server', 'Multi-tiered leading edge local area network', 1);
            insert into post (title, text, "creatorId") values ('challenge', 'Progressive full-range encoding', 1);
            insert into post (title, text, "creatorId") values ('Customer-focused', 'Profound secondary challenge', 1);
            insert into post (title, text, "creatorId") values ('challenge', 'Monitored demand-driven hub', 1);
            insert into post (title, text, "creatorId") values ('encoding', 'Cross-platform fault-tolerant software', 1);
            insert into post (title, text, "creatorId") values ('Face to face', 'Implemented dedicated projection', 1);
            insert into post (title, text, "creatorId") values ('solution-oriented', 'Customer-focused background application', 1);
            insert into post (title, text, "creatorId") values ('flexibility', 'Organic modular info-mediaries', 1);
            insert into post (title, text, "creatorId") values ('user-facing', 'Function-based tangible neural-net', 1);
            insert into post (title, text, "creatorId") values ('upward-trending', 'Re-engineered multimedia parallelism', 1);
            insert into post (title, text, "creatorId") values ('system-worthy', 'Optional zero administration database', 1);
            insert into post (title, text, "creatorId") values ('Distributed', 'Function-based neutral functionalities', 1);
            insert into post (title, text, "creatorId") values ('analyzing', 'Exclusive upward-trending internet solution', 1);
            insert into post (title, text, "creatorId") values ('Seamless', 'Progressive asynchronous framework', 1);
            insert into post (title, text, "creatorId") values ('Customer-focused', 'Optional local conglomeration', 1);
            insert into post (title, text, "creatorId") values ('explicit', 'Extended national info-mediaries', 1);
            insert into post (title, text, "creatorId") values ('Object-based', 'Mandatory explicit benchmark', 1);
            insert into post (title, text, "creatorId") values ('ability', 'Focused user-facing access', 1);
            insert into post (title, text, "creatorId") values ('hub', 'Self-enabling fresh-thinking framework', 1);
            insert into post (title, text, "creatorId") values ('bi-directional', 'Triple-buffered fault-tolerant circuit', 1);
            insert into post (title, text, "creatorId") values ('core', 'Multi-tiered neutral migration', 1);
            insert into post (title, text, "creatorId") values ('Persevering', 'Organized secondary workforce', 1);
            insert into post (title, text, "creatorId") values ('monitoring', 'Ameliorated bifurcated hierarchy', 1);
            insert into post (title, text, "creatorId") values ('function', 'Synergistic uniform protocol', 1);
            insert into post (title, text, "creatorId") values ('database', 'Upgradable mission-critical contingency', 1);
            insert into post (title, text, "creatorId") values ('full-range', 'Extended heuristic benchmark', 1);
            insert into post (title, text, "creatorId") values ('tertiary', 'Centralized reciprocal software', 1);
            insert into post (title, text, "creatorId") values ('bandwidth-monitored', 'Sharable system-worthy service-desk', 1);
            insert into post (title, text, "creatorId") values ('Persistent', 'Implemented stable artificial intelligence', 1);
            insert into post (title, text, "creatorId") values ('zero administration', 'Adaptive bifurcated project', 1);
            insert into post (title, text, "creatorId") values ('encompassing', 'Proactive multimedia hub', 1);
            insert into post (title, text, "creatorId") values ('national', 'Innovative 5th generation throughput', 1);
            insert into post (title, text, "creatorId") values ('motivating', 'Team-oriented foreground artificial intelligence', 1);
            insert into post (title, text, "creatorId") values ('empowering', 'Down-sized empowering neural-net', 1);
            insert into post (title, text, "creatorId") values ('Function-based', 'Exclusive dedicated intranet', 1);
            insert into post (title, text, "creatorId") values ('website', 'Cross-group methodical paradigm', 1);
        `);
	}

	public async down(queryRunner: QueryRunner): Promise<void> {}
}
